name: CD - Docker Publish

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    env:
      IMAGE: ${{ secrets.REGISTRY_USERNAME }}/${{ secrets.IMAGE_NAME }}:latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Debug IMAGE_NAME
        run: echo "::debug::IMAGE_NAME=${{ secrets.IMAGE_NAME }}"

      - name: Build da imagem Docker
        run: |
          docker build -t $IMAGE .

      - name: Push para Docker Hub
        run: |
          docker push $IMAGE