name: CD - Docker Publish

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build da imagem Docker
        run: |
          docker build -t ${{ secrets.IMAGE_NAME }}:latest .

      - name: Push da imagem para o Docker Hub
        run: |
          docker push ${{ secrets.IMAGE_NAME }}:latest
