name: CI - build, test and dockerize

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      DOTNET_VERSION: '8.0.x'

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instala o .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restaura dependências
        run: dotnet restore FIAP.CloudGames.sln

      - name: Compila solução
        run: dotnet build FIAP.CloudGames.sln --configuration Release --no-restore

      - name: Executa testes
        run: dotnet dotnet test --verbosity normal

      - name: Build da imagem Docker
        run: docker build -t cloudgames-api .
